spring:
  datasource:
    #url: jdbc:mariadb://192.168.99.100:3306/jmcustomer?useSSL=false&createDatabaseIfNotExist=true
    url: jdbc:mariadb://localhost:3306/jmcustomer?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
    connectionProperties:
      useUnicode: true
      characterEncoding: utf-8
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          format_sql: true
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: NON_EMPTY

server:
  port: 8006
#  servlet:
#    context-path: /customer
  compression:
    enabled: true
    mimeTypes: text/xml, text/css, text/html, application/json
    minResponseSize: 4096
